(setq mac-command-modifier 'meta)
(setq ns-function-modifier 'hyper)
(set-default-font "Monaco-15")
(defvar javascript-mode-syntax-table 'js-mode-syntax-table)
(menu-bar-mode)
(setq dired-use-ls-dired nil)
